### ISSUE TITLE
Active multi-currency

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#12]
![multi-divisa](https://cloud.githubusercontent.com/assets/6644187/21835803/700c9a4e-d785-11e6-8969-3a8852501eae.png)

**Comment by JesusZapata** [comment]
Done ! 
![image](https://cloud.githubusercontent.com/assets/1387970/21854148/0cf0c9d8-d7f0-11e6-8c39-5a5b899ab0c5.png)
