### ISSUE TITLE
Enable invoice_line.discount form view

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#16]
The group is: `sale.group_discount_per_so_line`
Then we need add `sale` to depends and assign this group to admin user

**Comment by JesusZapata** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/1387970/21946000/c564dad4-d9b4-11e6-98bf-02ff35fc3c51.png)

**Comment by moylop260** [comment]
Please, this concept is wrong because we won't need depend of sale to have this feature
Could you report this issue https://github.com/odoo/odoo/issues/new?

**Comment by moylop260** [comment]
@JesusZapata Did you create the issue?

**Comment by JesusZapata** [comment]
@moylop260 Done! https://github.com/odoo/odoo/issues/15094

**Comment by moylop260** [comment]
@JesusZapata 
Regression issue because odoo has new changes
Could you enabled again this option?

**Comment by JesusZapata** [comment]
@moylop260 
I don't understand, 
I downloaded last saas-14-odoo repository and enterprise-mx repository y this feature is work yet
I created dummy PR for this case https://github.com/Vauxoo/enterprise-mx/pull/35

Add screenshot of runbot
![image](https://cloud.githubusercontent.com/assets/1387970/22474932/d130e652-e7b3-11e6-8326-3666f93e2400.png)

**Comment by moylop260** [comment]
And the invoice is showing the discount field?
