### ISSUE TITLE
Configure MXN currency for company

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#19]
- [ ] Active MXN, USD and EUR currencies
- [ ] Use company.currency_id = base.MXN
- [ ] Delete all currency rates
- [ ] Enable multi-currency check from invoice settings

**Comment by JesusZapata** [comment]
@moylop260 
Check 1 and 2 are already done!
Should I do it again in this module?

**Comment by JesusZapata** [comment]
Check _Delete all currency rates_
![image](https://cloud.githubusercontent.com/assets/1387970/22023633/55816ebc-dc9d-11e6-80da-04da3ee87a00.png)

Check _Enable multi-currency check from invoice settings_
![image](https://cloud.githubusercontent.com/assets/1387970/22023606/3be294f4-dc9d-11e6-9802-e7e83681d545.png)

**Comment by JesusZapata** [comment]
Done !

![image](https://cloud.githubusercontent.com/assets/1387970/22072502/fc6ed562-dd78-11e6-96c3-e81c549e784a.png)
