### ISSUE TITLE
Enable multi-company settings boolean

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#21]
![screen shot 2017-01-18 at 7 14 25 am](https://cloud.githubusercontent.com/assets/6644187/22065267/1529686e-dd4d-11e6-83a8-d75db42d801f.png)

(Please, don't add a explicit group better use settings -> set value -> apply)

**Comment by JesusZapata** [comment]
@moylop260 
Screenshot on runbot

![image](https://cloud.githubusercontent.com/assets/1387970/22070917/f036ac34-dd73-11e6-99c9-431142d161db.png)

**Comment by JesusZapata** [comment]
![image](https://cloud.githubusercontent.com/assets/1387970/22072096/92ab012e-dd77-11e6-9cea-ad13dcddb9f7.png)
