### ISSUE TITLE
Enable attachments button from models

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#22]
![attachments](https://cloud.githubusercontent.com/assets/6644187/22066031/940aa26c-dd50-11e6-9b7b-468c16e5ceca.png)

(I don't remember how to enable it, but try installing document module or something similar)

**Comment by JesusZapata** [comment]
@moylop260 Done!

![image](https://cloud.githubusercontent.com/assets/1387970/22074361/7b13a74e-dd7e-11e6-9eb3-d2868eb9164c.png)
