### ISSUE TITLE
Load es_MX language

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#27]
...and set partner.lang=es_MX for all partners.

Using xml or yml you can call method to load lang method.

Using .travis.yml you can set lang to partners (see vx/mx) after all tests was executed

**Comment by JesusZapata** [comment]
@moylop260 
Done! 
![image](https://cloud.githubusercontent.com/assets/1387970/22109211/225154b2-de2d-11e6-959c-e6c7864e8a00.png)
