### ISSUE TITLE
[REF] l10n_mx_enterprise: Assign accounting adviser to "admin" user from data demo

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/enterprise-mx#7]
![borrar](https://cloud.githubusercontent.com/assets/6644187/21794135/29d4c538-d6bd-11e6-8e04-0f6a4c99dc62.png)

- [ ] Add print-screen to PR

**Comment by nhomar** [comment]
No cambien esto en demo por ahora pliz.

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by moylop260** [comment]
Yo necesito este cambio para no estarlo haciendo en cada build de runbot.
Ojo: Es enterprise-mx (no confundir con enterprise)

**Comment by nhomar** [comment]
Ah ok, para que el runbot lo haga?

**Comment by moylop260** [comment]
Sip

**Comment by JesusZapata** [comment]
I try to install this module and shows me next message :
`You try to install module 'l10n_mx_enterprise' that depends on module 'l10n_mx_edi'.
But the latter module is not available in your system.`
Where do I get this module?

**Comment by moylop260** [comment]
Could you send me the output of your t2d command?

**Comment by JesusZapata** [comment]
Forget it, I've deleted it and start over, and now it works fine.

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/enterprise-mx/pull/9
